### ISSUE TITLE
JOSS review comments

### ISSUE THREAD

**Issue by kperrynrel** [jranalli/solarspatialtools#11]
Hey Joe, still going through this but a couple of comments to start. I second all of @cwhanse's comments in https://github.com/jranalli/solartoolbox/issues/7 on adding in more specific function-level documentation and package scope information, so I'm going to focus on additional issues here.

Contribution and authorship: Has the submitting author (@jranalli) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

I'm not seeing your JPV and PVSC papers that leveraged this work in the documentation except in reference to specific functions. Should it be included here? 

![image](https://github.com/user-attachments/assets/da2cc39c-c861-4d11-b502-f0ac03402f29)

Installation instructions: Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.

The setup.py file does not include specific package versioning (particular minimum requirements). This should be in here, especially as the newer versions of pandas and numpy have consistently been wreaking havoc on several code bases.

**Comment by jranalli** [comment]
Good suggestion, I'll get the JPV paper in there. I was holding off on the PVSC ref, just because there's DOI for it yet, though I could list it as forthcoming. 

I did add a numpy version pin, because my tests were failing, but that was in a branch. I committed that part to `main` in #9 because that doesn't depend on some of these other concerns. It looks like I haven't had an issue with pandas yet, but I could add those just to be specific. 

On the API level docs, I did introduce a draft based on a pull request that you should be able [to preview here](https://solarspatialtools--10.org.readthedocs.build/en/10/). The name change is screwing up the outright deployment of that. I'm going to check in with Adam and see whether I can just try going ahead with it so that I can clean up the history of these issues a bit.

**Comment by jranalli** [comment]
Alright with the name changes through I actually implemented changes to this effect in a pull request.

**Comment by jranalli** [comment]
I believe these were addressed, but these comments would be superseded by comments made by the editors in the final JOSS review step.
