### ISSUE TITLE
Documentation shortcomings

### ISSUE THREAD

**Issue by cwhanse** [jranalli/solarspatialtools#7]
Below is the section about software documentation from the reviewer checklist for JOSS submissions. The only documentation is the README page. 

I am hesitant to check the unchecked items. My concerns are pasted below each check box item.

### Documentation

- [x] **A statement of need**: Do the authors clearly state what problems the software is designed to solve and who the target audience is?

The first paragraph of the README page should specify the scope of this package, which is tools for spatial analysis of solar-related data. This is clear from the paper. 

- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.

- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).

Twelve "demos" are included; some are jupyter notebooks, others are python scripts. The notebooks are adequately commented. `cmv_demo.ipynb` does not run (won't preview on github). `cmv_demo.py` has minimal commenting. 

It would be very helpful if the demos were rendered as documentation pages. Without any sort of introduction for new users, it is difficult to know where to enter these examples to learn how to use the tools in this package.

- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?

I don't think so. The primary failiing is the lack of a catalog of public functions. One must browse each code modules to discover what's available. Each function appears to be adequately documented, but checking again requires browsing each code file.

- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?

Without the benefit of API documentation, test coverage of public functions is difficult to judge.

- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

More could be provided on this topic. The single sentence doesn't convey a commitment by maintainers to support the package into the future.

**Comment by jranalli** [comment]
Thanks for these suggestions, it was motivation for me to learn how to use sphinx, though I admit in a very basic way. I built some API documentation that also gives some organization to the docs that I hope will address some of these comments. Changes are in the referencing pull request. 

I'm hesitating a bit to publish these right to a readthedocs project with #8 outstanding. I agree in principle that the name is somewhat generic. I'm not really sure whether there are potential consequences of changing it since it already exists on pypi, and I don't want to create that same problem on readthedocs if the name is up in the air. I was thinking of running the name discussion by the reviewers collectively to get feedback on whether a name change is recommended before trying to resolve that.  

Given that: @cwhanse for now do you feel it's reasonable to generate the sphinx docs locally for the referenced PR to take a look and see if they address your concerns? If not I'll gladly just jump and get them on readthedocs ASAP.

**Comment by cwhanse** [comment]
I think its better to get agreement on the package name, and then I can look at the docs.

**Comment by jranalli** [comment]
A draft of the documentation for a renamed package based on pull request #10 is available on [readthedocs](https://solarspatialtools--10.org.readthedocs.build/en/10/).

**Comment by jranalli** [comment]
Alright, having gone through with the rename, the latest published version has tried to address many of these comments, and there are [API docs](https://solarspatialtools.readthedocs.io/en/stable/) corresponding to the latest version along with it. If there are still concerns, please let me know so I can address them.

**Comment by cwhanse** [comment]
@jranalli the revisions answer my concerns about documentation.
