### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by cwhanse** [jranalli/solarspatialtools#8]
`solartoolbox` is quite generic - perhaps something like `solarspatialtools` would better convey the intended scope?

**Comment by jranalli** [comment]
While I agree in principle that the name is somewhat generic, my personal preference would be to leave it, if only for logistical reasons. But I would be happy to consider further feedback and opinions as part of this process.

**Comment by AdamRJensen** [comment]
@jranalli if you do decide to change the name, then I would suggest waiting until all reviews have been completed (though I see that @cwhanse suggests otherwise, so your choice). With that said, I'm inclined to agree that it's very generic, and if the package will remain specific to spatial analysis then I think it makes sense to change the name.

**Comment by jranalli** [comment]
I'm going to go ahead with this proposal, but as @AdamRJensen suggested, I will either delay the actual renaming of the GitHub repository, or wait until there's a bit more clarity about potential impacts on the JOSS review process. I believe that there may not be big impacts, because after checking on a test repository, it appears that GitHub automatically redirects things, but I'll follow whatever guidance JOSS has on this.

I don't think I can change over my github actions for the pypi publishing until I've renamed things here on GitHub so that will have to wait until the GitHub renaming is resolved.

**Comment by jranalli** [comment]
Installation is currently available via testpypi for anyone who wanted to use that pathway. 

`pip install -i https://test.pypi.org/simple/ solarspatialtools`

**Comment by kperrynrel** [comment]
I'm going through my JOSS review right now, and I am also inclined for changing the name here to solarspatialtools, as solartoolbox is generic and is thrown around a lot for different applications when I do a quick Google search on it. Adding my opinion in here as I know you were interested in getting a consensus on this @jranalli

**Comment by kbonney** [comment]
Sounds like you have made up your mind @jranalli, but my personal 2 cents is that the name `solartoolbox` while generic, did suit the repository since it is intended to be a catchall for various PV functionality that falls outside of the scope of the major packages. Either way works for me, though.

**Comment by jranalli** [comment]
Name changed and pushed. Still will need some checking to ensure that publishing to pypi and readthedocs works.
